
job_1:
- fit_rates_weighted_average:
    model_type: association
- fit_gibbs_global_batch:
    reference: SecB WT apo
    epochs: 200000
    stop_loss: 1.e-5
    patience: 100
    optimizer: SGD
    lr: 1.e+4
    momentum: 0.5
    nesterov: True